name: Test
on:
  push:
  workflow_dispatch:
concurrency:
  group: test
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        number: [0, 1, 2, 3]
        include:
          - builder: true
          - number: 0
            builder: false

    name: ${{ matrix.number }} 
    steps:
      - name: Write file
        uses: "DamianReeves/write-file-action@master"
        if: matrix.builder
        with:
          path: data-${{ matrix.number }}.txt
          write-mode: overwrite
          contents: |
            test
      - if: matrix.builder
        run: sleep 10
      - name: Upload
        uses: actions/upload-artifact@v4
        if: matrix.builder
        with:
          name: data-${{ matrix.number }}-${{ github.run_attempt }}
          path: data-${{ matrix.number }}.txt
      - if: ${{ ! matrix.builder }}
        run: |
          import requests
          response=requests.get("https://api.github.com/repos/physics-enthusiast/misc-actions-testing-v2/actions/artifacts", headers={"Accept":"application/vnd.github+json", "X-GitHub-Api-Version":"2022-11-28"})
          print(response)
        shell: python
